import type { Metadata } from "next";
import { Session } from 'next-auth';
import AuthProvider from "./authProvider";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    pageProps, // No need to destructure `session` here directly
    session
}: {
    children: React.ReactNode;
    pageProps: any;
    session: Session
}) {
    return (
        <html lang="en">
            <body>
                {/* Wrap the app in SessionProvider */}
                <AuthProvider session={session}>
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
